hw5
Ornstein385/tinkoff-java-course pull request #5
Opened 2024-03-17 19:36 UTC by Ornstein385

2024-03-24 09:52 UTC, YuriiKondratov commented
Привет! Раздели пожалуйста "ДЗ 5" и "ДЗ 5: Бонус" на два разных PR`а.

2024-03-24 10:38 UTC, YuriiKondratov requested changes
Выше указал

2024-03-27 12:48 UTC, YuriiKondratov requested changes

2024-03-27 12:48 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/jdbc/service/JdbcLinkService.java
> +        chatDao.addChat(new ChatDto(tgChatId, null));
почему при добавлении ссылки к чату ты добавляешь чат с этим айди? У тебя же по идее этот чат уже существует в базе и ты просто к нему ссылку подвязать должен

2024-03-27 12:48 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        AtomicLong idGenerator = new AtomicLong(1);
Тут вообще не понял что происходит. Ты же достаешь из базы ссылки у которых уже есть свои айдишники. Почему ты их (айдишники) не передаешь из сервиса, а тут опять пытаешься генерировать?

2024-03-27 12:48 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/jdbc/service/JdbcLinkService.java
> +            .orElseThrow(() -> new NoSuchElementException("не был найден URL при добавлении: " + url))
А как ссылка может быть не найдена, если ты её строчкой выше добавил?

2024-03-30 12:06 UTC, Ornstein385 commented on scrapper/src/main/java/edu/java/jdbc/service/JdbcLinkService.java
> +        chatDao.addChat(new ChatDto(tgChatId, null));
смысл был в том, чтобы при выполнении add(long tgChatId, URI url) создать чат, если он не был создан ранее. однако убрал это.

2024-03-30 12:13 UTC, Ornstein385 commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        AtomicLong idGenerator = new AtomicLong(1);
LinkService работает с объектами
@Data
public class Link {
    private URI url;
    private OffsetDateTime lastUpdated;
}
а не с dto из базы данных. и эти самые dto будут отличаться от способа подключения, например jpa-реализация будет работать с Entity-классами. и в целом мне не кажется хорошей идеей вытаскивать id из таблицы во внешний мир

2024-03-30 12:16 UTC, Ornstein385 commented on scrapper/src/main/java/edu/java/jdbc/service/JdbcLinkService.java
> +            .orElseThrow(() -> new NoSuchElementException("не был найден URL при добавлении: " + url))
могла не завершиться транзакция на уровне базы данных, а так у приложения будет адекватный способ об этом узнать. однако убрал это

2024-04-07 06:30 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/jdbc/service/JdbcLinkService.java
> +        chatDao.addChat(new ChatDto(tgChatId, null));
если чат не был создан до добавления ссылки - это ошибка. В таком случае надо выбрасывать эксепшн и как-то реагировать на эту ошибку, но молча создавать новый чат - плохая идея.

2024-04-07 06:34 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/controller/LinksController.java
> +        AtomicLong idGenerator = new AtomicLong(1);
не вижу ничего плохого в передаче айдишников во внешний мир. Это же не какая-то sensitive data, это грубо говоря "ссылка" на объект в базе. Если клиент захочет получить дополнительную информацию об объекте, то он будет использовать для этого эту ссылку (айдишник)

2024-04-07 06:36 UTC, YuriiKondratov commented on scrapper/src/main/java/edu/java/jdbc/service/JdbcLinkService.java
> +            .orElseThrow(() -> new NoSuchElementException("не был найден URL при добавлении: " + url))
Если тебе здесь нужна транзакционность, то лучше объединить это всё в одну транзакцию (повесить transactional на метод)

2024-04-07 06:36 UTC, YuriiKondratov approved these changes

2024-04-21 23:45 UTC, closed without merging